### ISSUE TITLE
Feature - Implementar página de organizações

### ISSUE THREAD

**Issue by RodrigoEC** [Guardians-DSC/Front-HoCo#12]
### Descrição

Implementar página de `organizações`.

**Figma para ver melhor o design do componente:** https://www.figma.com/file/e62phNSSNY2C1kgAOCFfid/HoCo?node-id=640%3A2271

### Print do componente

![image](https://user-images.githubusercontent.com/42751604/132910902-52359e66-a7ff-40bf-81e5-1cc6f618f4a1.png)

**Comment by RuanGOA** [comment]
Eu poderia ficar com essa issue e com a #4, sobre cards de organizações? Mesmo essa estando _disabled_, acredito que a única dependência seria o componente de organizações, imagino.

**Comment by RodrigoEC** [comment]
pode simm
