### ISSUE TITLE
Feature - Implementar página de sobre

### ISSUE THREAD

**Issue by RodrigoEC** [Guardians-DSC/Front-HoCo#13]
### Descrição

Implementar página de `sobre`.

**Figma para ver melhor o design do componente:** https://www.figma.com/file/e62phNSSNY2C1kgAOCFfid/HoCo?node-id=640%3A2271

### Print do componente

![image](https://user-images.githubusercontent.com/42751604/132911061-4effe532-4fd1-45a8-9089-a7d5dae7adab.png)

**Comment by RuanGOA** [comment]
Pessoal, como a issue #6 está atribuída a mim, pensei que eu poderia ficar com esta também, já que elas são bem relacionadas, pode ser?

**Comment by RodrigoEC** [comment]
Feito!
