### ISSUE TITLE
Feature - Implementar componente OrgaCard

### ISSUE THREAD

**Issue by RodrigoEC** [Guardians-DSC/Front-HoCo#4]
### Descrição

Implementar componente `OrgCard`. O componente serve como link para o site da organização.

A ideia é que o card possua a logo da org e uma vez que o usuário passe o mouse por cima do componente o nom da org aparece. Caso o usuário clique no card ele/ela é redirecionada para o site da organização.

**Figma para ver melhor o design do componente:** https://www.figma.com/file/e62phNSSNY2C1kgAOCFfid/HoCo?node-id=640%3A2271

### Print do componente

**On mouse out**
<span><img width=500px src='https://user-images.githubusercontent.com/42751604/132905265-6a7c2cbb-fe66-46d0-87bc-d30974e76d49.png'/></span>

**On mouse over**
<span><img width=500px src='https://user-images.githubusercontent.com/42751604/132905206-8ce6cce5-7ae3-4d6e-9951-51d66848895d.png'/></span>

**Comment by RuanGOA** [comment]
Como citei na issue #12, já que essa issue e a outra estão relacionadas, acredito que seria uma ficar com as duas, se possível.

**Comment by RodrigoEC** [comment]
Feito :)
