### ISSUE TITLE
Feature - Recuperar contribuidores do projeto no github

### ISSUE THREAD

**Issue by RodrigoEC** [Guardians-DSC/Front-HoCo#6]
### Descrição

Implementar a integração do projeto com os repositórios do github do hoco, os três existentes atualmente, e sumarizar os seus contribuidores. 
Uma vez integrado com a API do github é interessante fazer a visualização dos contribuidores, mostrando uma foto de cada contriibuidor e quando o usuário clicar na foto a pessoa é redirecionada para o perfil do usuário

**Figma para ver melhor o design:** https://www.figma.com/file/e62phNSSNY2C1kgAOCFfid/HoCo?node-id=640%3A2271

### Print de exemplo
![image](https://user-images.githubusercontent.com/42751604/132907508-1b3cd4e9-9af1-4420-809e-46de7f1ff2f2.png)

**Comment by RuanGOA** [comment]
Estava lendo as issues, e acredito que eu possa ajudar com essa. Poderia atribuir ela para mim?

**Comment by RodrigoEC** [comment]
Posso sim!
